mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
proxies:
- name: 🇫🇮 Finland Hysteria2
  type: hysteria2
  server: cloudioxa.duckdns.org
  port: 443
  password: default:zG7yqufT5HccjgnMVaCdOwB0
  sni: cloudioxa.duckdns.org
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - 🇫🇮 Finland Hysteria2
rules:
- MATCH,PROXY
